name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev, qa, prod]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "✅ Building application..."
          echo "✅ CI completed successfully"
